[2022-06-22 08:38:05,401] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_24 manual__2022-06-22T08:37:57.153993+00:00 [queued]>
[2022-06-22 08:38:05,433] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_24 manual__2022-06-22T08:37:57.153993+00:00 [queued]>
[2022-06-22 08:38:05,433] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 08:38:05,434] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-22 08:38:05,434] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 08:38:05,469] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): START_COUNT_BY_DAY_24> on 2022-06-22 08:37:57.153993+00:00
[2022-06-22 08:38:05,480] {standard_task_runner.py:52} INFO - Started process 2891 to run task
[2022-06-22 08:38:05,529] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'START_COUNT_BY_DAY_24', 'manual__2022-06-22T08:37:57.153993+00:00', '--job-id', '1042', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmpo42bxtax', '--error-file', '/tmp/tmp277ko081']
[2022-06-22 08:38:05,531] {standard_task_runner.py:77} INFO - Job 1042: Subtask START_COUNT_BY_DAY_24
[2022-06-22 08:38:05,791] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_24 manual__2022-06-22T08:37:57.153993+00:00 [running]> on host a0a302277daf
[2022-06-22 08:38:06,461] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=START_COUNT_BY_DAY_24
AIRFLOW_CTX_EXECUTION_DATE=2022-06-22T08:37:57.153993+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-22T08:37:57.153993+00:00
[2022-06-22 08:38:06,489] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-22 08:38:06,495] {dbapi.py:225} INFO - Running statement: CALL ds.fill_account_turnover_f (%(date)s::date);, parameters: {'date': '2018-01-24'}
[2022-06-22 08:38:07,576] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=START_COUNT_BY_DAY_24, execution_date=20220622T083757, start_date=20220622T083805, end_date=20220622T083807
[2022-06-22 08:38:07,675] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-22 08:38:08,683] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
