[2022-06-21 14:04:28,882] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.create_log_tables manual__2022-06-21T14:04:26.269664+00:00 [queued]>
[2022-06-21 14:04:28,900] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.create_log_tables manual__2022-06-21T14:04:26.269664+00:00 [queued]>
[2022-06-21 14:04:28,903] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 14:04:28,903] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-21 14:04:28,903] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 14:04:28,928] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_log_tables> on 2022-06-21 14:04:26.269664+00:00
[2022-06-21 14:04:28,933] {standard_task_runner.py:52} INFO - Started process 767 to run task
[2022-06-21 14:04:28,936] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'create_log_tables', 'manual__2022-06-21T14:04:26.269664+00:00', '--job-id', '523', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmpf4ak_yem', '--error-file', '/tmp/tmp5z5kzyah']
[2022-06-21 14:04:28,937] {standard_task_runner.py:77} INFO - Job 523: Subtask create_log_tables
[2022-06-21 14:04:29,031] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.create_log_tables manual__2022-06-21T14:04:26.269664+00:00 [running]> on host c087b85f9f15
[2022-06-21 14:04:29,087] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=create_log_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T14:04:26.269664+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-21T14:04:26.269664+00:00
[2022-06-21 14:04:29,096] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-21 14:04:29,101] {dbapi.py:225} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS logs;
CREATE SCHEMA IF NOT EXISTS dm;
CREATE SEQUENCE IF NOT EXISTS dm.seq_lg_messages INCREMENT 1 START 1;


CREATE TABLE IF NOT EXISTS logs.load_csv_to_ds (
    ID SERIAL PRIMARY KEY,
    TABLE_NAME VARCHAR(30),
    CSV_PATH TEXT,
    TIME_START_LOAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0),
    TIME_END_LOAD TIMESTAMP,
    condition TEXT
);


CREATE TABLE IF NOT EXISTS dm.lg_messages ( 	
    record_id INT,
    date_time TIMESTAMP,
    pid TEXT,
    message TEXT,
    message_type TEXT,
    usename TEXT, 
    datname TEXT, 
    client_addr TEXT, 
    application_name TEXT,
    backend_start TEXT
);, parameters: None
[2022-06-21 14:04:29,103] {postgres.py:71} INFO - NOTICE:  schema "logs" already exists, skipping

[2022-06-21 14:04:29,103] {postgres.py:71} INFO - NOTICE:  schema "dm" already exists, skipping

[2022-06-21 14:04:29,103] {postgres.py:71} INFO - NOTICE:  relation "seq_lg_messages" already exists, skipping

[2022-06-21 14:04:29,103] {postgres.py:71} INFO - NOTICE:  relation "load_csv_to_ds" already exists, skipping

[2022-06-21 14:04:29,103] {postgres.py:71} INFO - NOTICE:  relation "lg_messages" already exists, skipping

[2022-06-21 14:04:29,142] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=create_log_tables, execution_date=20220621T140426, start_date=20220621T140428, end_date=20220621T140429
[2022-06-21 14:04:29,192] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-21 14:04:29,255] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
