[2022-06-18 15:14:33,439] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_10 manual__2022-06-18T15:14:12.826519+00:00 [queued]>
[2022-06-18 15:14:33,580] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_10 manual__2022-06-18T15:14:12.826519+00:00 [queued]>
[2022-06-18 15:14:33,593] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 15:14:33,593] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-18 15:14:33,593] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 15:14:33,642] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): START_COUNT_BY_DAY_10> on 2022-06-18 15:14:12.826519+00:00
[2022-06-18 15:14:33,648] {standard_task_runner.py:52} INFO - Started process 1848 to run task
[2022-06-18 15:14:33,673] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'START_COUNT_BY_DAY_10', 'manual__2022-06-18T15:14:12.826519+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmp8ciwcobd', '--error-file', '/tmp/tmp28dbiijx']
[2022-06-18 15:14:33,674] {standard_task_runner.py:77} INFO - Job 168: Subtask START_COUNT_BY_DAY_10
[2022-06-18 15:14:33,940] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_10 manual__2022-06-18T15:14:12.826519+00:00 [running]> on host 191dd4d3d1ba
[2022-06-18 15:14:34,128] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=START_COUNT_BY_DAY_10
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T15:14:12.826519+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-18T15:14:12.826519+00:00
[2022-06-18 15:14:34,153] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-18 15:14:34,168] {dbapi.py:225} INFO - Running statement: CALL ds.fill_account_turnover_f (%(date)s::date);, parameters: {'date': '2018-01-10'}
[2022-06-18 15:14:35,073] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=START_COUNT_BY_DAY_10, execution_date=20220618T151412, start_date=20220618T151433, end_date=20220618T151435
[2022-06-18 15:14:35,155] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-18 15:14:35,976] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
