[2022-06-22 08:38:10,278] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_11 manual__2022-06-22T08:37:57.153993+00:00 [queued]>
[2022-06-22 08:38:10,340] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_11 manual__2022-06-22T08:37:57.153993+00:00 [queued]>
[2022-06-22 08:38:10,341] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 08:38:10,341] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-22 08:38:10,341] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 08:38:10,387] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): START_COUNT_BY_DAY_11> on 2022-06-22 08:37:57.153993+00:00
[2022-06-22 08:38:10,407] {standard_task_runner.py:52} INFO - Started process 2930 to run task
[2022-06-22 08:38:10,484] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'START_COUNT_BY_DAY_11', 'manual__2022-06-22T08:37:57.153993+00:00', '--job-id', '1047', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmpws70u11w', '--error-file', '/tmp/tmpnhc6bj4k']
[2022-06-22 08:38:10,485] {standard_task_runner.py:77} INFO - Job 1047: Subtask START_COUNT_BY_DAY_11
[2022-06-22 08:38:10,939] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_11 manual__2022-06-22T08:37:57.153993+00:00 [running]> on host a0a302277daf
[2022-06-22 08:38:12,093] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=START_COUNT_BY_DAY_11
AIRFLOW_CTX_EXECUTION_DATE=2022-06-22T08:37:57.153993+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-22T08:37:57.153993+00:00
[2022-06-22 08:38:12,129] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-22 08:38:12,144] {dbapi.py:225} INFO - Running statement: CALL ds.fill_account_turnover_f (%(date)s::date);, parameters: {'date': '2018-01-11'}
[2022-06-22 08:38:12,865] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=START_COUNT_BY_DAY_11, execution_date=20220622T083757, start_date=20220622T083810, end_date=20220622T083812
[2022-06-22 08:38:12,970] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-22 08:38:13,507] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
