[2022-06-21 06:27:44,297] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.create_log_tables scheduled__2022-06-19T21:27:30.430782+00:00 [queued]>
[2022-06-21 06:27:44,321] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.create_log_tables scheduled__2022-06-19T21:27:30.430782+00:00 [queued]>
[2022-06-21 06:27:44,321] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 06:27:44,322] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-21 06:27:44,322] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 06:27:44,357] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_log_tables> on 2022-06-19 21:27:30.430782+00:00
[2022-06-21 06:27:44,373] {standard_task_runner.py:52} INFO - Started process 79 to run task
[2022-06-21 06:27:44,401] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'create_log_tables', 'scheduled__2022-06-19T21:27:30.430782+00:00', '--job-id', '436', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmp_w1atxv7', '--error-file', '/tmp/tmpey4962fc']
[2022-06-21 06:27:44,402] {standard_task_runner.py:77} INFO - Job 436: Subtask create_log_tables
[2022-06-21 06:27:44,735] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.create_log_tables scheduled__2022-06-19T21:27:30.430782+00:00 [running]> on host c087b85f9f15
[2022-06-21 06:27:44,936] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=create_log_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-06-19T21:27:30.430782+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-19T21:27:30.430782+00:00
[2022-06-21 06:27:44,989] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-21 06:27:45,009] {dbapi.py:225} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS logs;
CREATE SCHEMA IF NOT EXISTS dm;
CREATE SEQUENCE IF NOT EXISTS dm.seq_lg_messages INCREMENT 1 START 1;


CREATE TABLE IF NOT EXISTS logs.load_csv_to_ds (
    ID SERIAL PRIMARY KEY,
    TABLE_NAME VARCHAR(30),
    CSV_PATH TEXT,
    TIME_START_LOAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0),
    TIME_END_LOAD TIMESTAMP,
    condition TEXT
);


CREATE TABLE IF NOT EXISTS dm.lg_messages ( 	
    record_id INT,
    date_time TIMESTAMP,
    pid TEXT,
    message TEXT,
    message_type TEXT,
    usename TEXT, 
    datname TEXT, 
    client_addr TEXT, 
    application_name TEXT,
    backend_start TEXT
);, parameters: None
[2022-06-21 06:27:45,019] {postgres.py:71} INFO - NOTICE:  schema "logs" already exists, skipping

[2022-06-21 06:27:45,019] {postgres.py:71} INFO - NOTICE:  schema "dm" already exists, skipping

[2022-06-21 06:27:45,019] {postgres.py:71} INFO - NOTICE:  relation "seq_lg_messages" already exists, skipping

[2022-06-21 06:27:45,019] {postgres.py:71} INFO - NOTICE:  relation "load_csv_to_ds" already exists, skipping

[2022-06-21 06:27:45,019] {postgres.py:71} INFO - NOTICE:  relation "lg_messages" already exists, skipping

[2022-06-21 06:27:45,166] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=create_log_tables, execution_date=20220619T212730, start_date=20220621T062744, end_date=20220621T062745
[2022-06-21 06:27:45,251] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-21 06:27:45,401] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
