[2022-06-21 14:38:11,339] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_10 manual__2022-06-21T14:38:00.740001+00:00 [queued]>
[2022-06-21 14:38:11,423] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_10 manual__2022-06-21T14:38:00.740001+00:00 [queued]>
[2022-06-21 14:38:11,424] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 14:38:11,424] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-21 14:38:11,424] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 14:38:11,511] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): START_COUNT_BY_DAY_10> on 2022-06-21 14:38:00.740001+00:00
[2022-06-21 14:38:11,543] {standard_task_runner.py:52} INFO - Started process 3072 to run task
[2022-06-21 14:38:11,563] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'START_COUNT_BY_DAY_10', 'manual__2022-06-21T14:38:00.740001+00:00', '--job-id', '791', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmpf4014gai', '--error-file', '/tmp/tmph9_tod80']
[2022-06-21 14:38:11,564] {standard_task_runner.py:77} INFO - Job 791: Subtask START_COUNT_BY_DAY_10
[2022-06-21 14:38:11,747] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_10 manual__2022-06-21T14:38:00.740001+00:00 [running]> on host c087b85f9f15
[2022-06-21 14:38:11,898] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=START_COUNT_BY_DAY_10
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T14:38:00.740001+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-21T14:38:00.740001+00:00
[2022-06-21 14:38:11,935] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-21 14:38:11,959] {dbapi.py:225} INFO - Running statement: CALL ds.fill_account_turnover_f (%(date)s::date);, parameters: {'date': '2018-01-10'}
[2022-06-21 14:38:12,703] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=START_COUNT_BY_DAY_10, execution_date=20220621T143800, start_date=20220621T143811, end_date=20220621T143812
[2022-06-21 14:38:12,779] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-21 14:38:13,464] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
