[2022-06-21 14:47:20,088] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_22 manual__2022-06-21T14:47:12.417122+00:00 [queued]>
[2022-06-21 14:47:20,111] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_22 manual__2022-06-21T14:47:12.417122+00:00 [queued]>
[2022-06-21 14:47:20,112] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 14:47:20,115] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-21 14:47:20,115] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 14:47:20,143] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): START_COUNT_BY_DAY_22> on 2022-06-21 14:47:12.417122+00:00
[2022-06-21 14:47:20,157] {standard_task_runner.py:52} INFO - Started process 3547 to run task
[2022-06-21 14:47:20,175] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'START_COUNT_BY_DAY_22', 'manual__2022-06-21T14:47:12.417122+00:00', '--job-id', '818', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmp93w_cemu', '--error-file', '/tmp/tmp6j4d1hdd']
[2022-06-21 14:47:20,176] {standard_task_runner.py:77} INFO - Job 818: Subtask START_COUNT_BY_DAY_22
[2022-06-21 14:47:20,364] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_22 manual__2022-06-21T14:47:12.417122+00:00 [running]> on host c087b85f9f15
[2022-06-21 14:47:20,547] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=START_COUNT_BY_DAY_22
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T14:47:12.417122+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-21T14:47:12.417122+00:00
[2022-06-21 14:47:20,582] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-21 14:47:20,620] {dbapi.py:225} INFO - Running statement: CALL ds.fill_account_turnover_f (%(date)s::date);, parameters: {'date': '2018-01-22'}
[2022-06-21 14:47:21,089] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=START_COUNT_BY_DAY_22, execution_date=20220621T144712, start_date=20220621T144720, end_date=20220621T144721
[2022-06-21 14:47:21,143] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-21 14:47:22,507] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
