[2022-06-22 21:01:04,583] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: f101_from_csv_to_db.create_double_101f_if_not_exists manual__2022-06-22T21:01:02.360561+00:00 [queued]>
[2022-06-22 21:01:04,591] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: f101_from_csv_to_db.create_double_101f_if_not_exists manual__2022-06-22T21:01:02.360561+00:00 [queued]>
[2022-06-22 21:01:04,591] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 21:01:04,591] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-22 21:01:04,591] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 21:01:04,600] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_double_101f_if_not_exists> on 2022-06-22 21:01:02.360561+00:00
[2022-06-22 21:01:04,604] {standard_task_runner.py:52} INFO - Started process 4211 to run task
[2022-06-22 21:01:04,607] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'f101_from_csv_to_db', 'create_double_101f_if_not_exists', 'manual__2022-06-22T21:01:02.360561+00:00', '--job-id', '1148', '--raw', '--subdir', 'DAGS_FOLDER/f101_from_local.py', '--cfg-path', '/tmp/tmpfs6h4wo9', '--error-file', '/tmp/tmpvwdide_6']
[2022-06-22 21:01:04,608] {standard_task_runner.py:77} INFO - Job 1148: Subtask create_double_101f_if_not_exists
[2022-06-22 21:01:04,655] {logging_mixin.py:109} INFO - Running <TaskInstance: f101_from_csv_to_db.create_double_101f_if_not_exists manual__2022-06-22T21:01:02.360561+00:00 [running]> on host bc39be91d060
[2022-06-22 21:01:04,700] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=f101_from_csv_to_db
AIRFLOW_CTX_TASK_ID=create_double_101f_if_not_exists
AIRFLOW_CTX_EXECUTION_DATE=2022-06-22T21:01:02.360561+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-22T21:01:02.360561+00:00
[2022-06-22 21:01:04,706] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-22 21:01:04,710] {dbapi.py:225} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS dm.dm_f101_round_f_v2 
            AS (SELECT * from dm.dm_f101_round_f) with no data;
            , parameters: None
[2022-06-22 21:01:04,711] {postgres.py:71} INFO - NOTICE:  relation "dm_f101_round_f_v2" already exists, skipping

[2022-06-22 21:01:04,719] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=f101_from_csv_to_db, task_id=create_double_101f_if_not_exists, execution_date=20220622T210102, start_date=20220622T210104, end_date=20220622T210104
[2022-06-22 21:01:04,740] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-22 21:01:04,769] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
