[2022-06-18 15:14:27,640] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_3 manual__2022-06-18T15:14:12.504350+00:00 [queued]>
[2022-06-18 15:14:27,705] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_3 manual__2022-06-18T15:14:12.504350+00:00 [queued]>
[2022-06-18 15:14:27,705] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 15:14:27,705] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-18 15:14:27,705] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 15:14:27,859] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): START_COUNT_BY_DAY_3> on 2022-06-18 15:14:12.504350+00:00
[2022-06-18 15:14:27,910] {standard_task_runner.py:52} INFO - Started process 1806 to run task
[2022-06-18 15:14:27,973] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'START_COUNT_BY_DAY_3', 'manual__2022-06-18T15:14:12.504350+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmpfzhmkpgo', '--error-file', '/tmp/tmp2w2pafst']
[2022-06-18 15:14:27,986] {standard_task_runner.py:77} INFO - Job 154: Subtask START_COUNT_BY_DAY_3
[2022-06-18 15:14:28,297] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_3 manual__2022-06-18T15:14:12.504350+00:00 [running]> on host 191dd4d3d1ba
[2022-06-18 15:14:28,695] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=START_COUNT_BY_DAY_3
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T15:14:12.504350+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-18T15:14:12.504350+00:00
[2022-06-18 15:14:28,741] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-18 15:14:28,761] {dbapi.py:225} INFO - Running statement: CALL ds.fill_account_turnover_f (%(date)s::date);, parameters: {'date': '2018-01-3'}
[2022-06-18 15:14:29,043] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=START_COUNT_BY_DAY_3, execution_date=20220618T151412, start_date=20220618T151427, end_date=20220618T151429
[2022-06-18 15:14:29,227] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-18 15:14:30,224] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
