[2022-06-21 14:32:13,530] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-f101_round_f.create_log_tables manual__2022-06-21T14:32:11.929204+00:00 [queued]>
[2022-06-21 14:32:13,541] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-f101_round_f.create_log_tables manual__2022-06-21T14:32:11.929204+00:00 [queued]>
[2022-06-21 14:32:13,542] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 14:32:13,542] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-21 14:32:13,542] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 14:32:13,554] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_log_tables> on 2022-06-21 14:32:11.929204+00:00
[2022-06-21 14:32:13,561] {standard_task_runner.py:52} INFO - Started process 2632 to run task
[2022-06-21 14:32:13,566] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-f101_round_f', 'create_log_tables', 'manual__2022-06-21T14:32:11.929204+00:00', '--job-id', '737', '--raw', '--subdir', 'DAGS_FOLDER/f_101_round_f.py', '--cfg-path', '/tmp/tmpn0qvroej', '--error-file', '/tmp/tmph2am2etg']
[2022-06-21 14:32:13,567] {standard_task_runner.py:77} INFO - Job 737: Subtask create_log_tables
[2022-06-21 14:32:13,642] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-f101_round_f.create_log_tables manual__2022-06-21T14:32:11.929204+00:00 [running]> on host c087b85f9f15
[2022-06-21 14:32:13,706] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-f101_round_f
AIRFLOW_CTX_TASK_ID=create_log_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T14:32:11.929204+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-21T14:32:11.929204+00:00
[2022-06-21 14:32:13,720] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-21 14:32:13,724] {dbapi.py:225} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS logs;
CREATE SEQUENCE IF NOT EXISTS logs.seq_lg_messages INCREMENT 1 START 1;


CREATE TABLE IF NOT EXISTS logs.load_csv_to_ds (
    ID SERIAL PRIMARY KEY,
    TABLE_NAME VARCHAR(30),
    CSV_PATH TEXT,
    TIME_START_LOAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0),
    TIME_END_LOAD TIMESTAMP,
    condition TEXT
);


CREATE TABLE IF NOT EXISTS logs.lg_messages_dm ( 	
    record_id INT,
    date_time TIMESTAMP,
    pid TEXT,
    message TEXT,
    message_type TEXT,
    usename TEXT, 
    datname TEXT, 
    client_addr TEXT, 
    application_name TEXT,
    backend_start TEXT
);, parameters: None
[2022-06-21 14:32:13,724] {postgres.py:71} INFO - NOTICE:  schema "logs" already exists, skipping

[2022-06-21 14:32:13,725] {postgres.py:71} INFO - NOTICE:  relation "seq_lg_messages" already exists, skipping

[2022-06-21 14:32:13,725] {postgres.py:71} INFO - NOTICE:  relation "load_csv_to_ds" already exists, skipping

[2022-06-21 14:32:13,725] {postgres.py:71} INFO - NOTICE:  relation "lg_messages_dm" already exists, skipping

[2022-06-21 14:32:13,771] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-f101_round_f, task_id=create_log_tables, execution_date=20220621T143211, start_date=20220621T143213, end_date=20220621T143213
[2022-06-21 14:32:13,820] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-21 14:32:13,860] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
