[2022-06-22 08:38:05,650] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_19 manual__2022-06-22T08:37:57.153993+00:00 [queued]>
[2022-06-22 08:38:05,715] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_19 manual__2022-06-22T08:37:57.153993+00:00 [queued]>
[2022-06-22 08:38:05,715] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 08:38:05,715] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-22 08:38:05,715] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 08:38:05,804] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): START_COUNT_BY_DAY_19> on 2022-06-22 08:37:57.153993+00:00
[2022-06-22 08:38:05,829] {standard_task_runner.py:52} INFO - Started process 2893 to run task
[2022-06-22 08:38:05,858] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'START_COUNT_BY_DAY_19', 'manual__2022-06-22T08:37:57.153993+00:00', '--job-id', '1044', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmpug4matbs', '--error-file', '/tmp/tmp1pl_9p7b']
[2022-06-22 08:38:05,859] {standard_task_runner.py:77} INFO - Job 1044: Subtask START_COUNT_BY_DAY_19
[2022-06-22 08:38:06,082] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.START_COUNT_BY_DAY_19 manual__2022-06-22T08:37:57.153993+00:00 [running]> on host a0a302277daf
[2022-06-22 08:38:06,312] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=START_COUNT_BY_DAY_19
AIRFLOW_CTX_EXECUTION_DATE=2022-06-22T08:37:57.153993+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-22T08:37:57.153993+00:00
[2022-06-22 08:38:06,335] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-22 08:38:06,355] {dbapi.py:225} INFO - Running statement: CALL ds.fill_account_turnover_f (%(date)s::date);, parameters: {'date': '2018-01-19'}
[2022-06-22 08:38:07,406] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=START_COUNT_BY_DAY_19, execution_date=20220622T083757, start_date=20220622T083805, end_date=20220622T083807
[2022-06-22 08:38:07,504] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-22 08:38:08,520] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
